version: '3.8'
services:
  recipes-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipes-api 
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    container_name: postgres_recipes
    restart: always
    ports:
      - 5432:5432
    
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres:
    name: nest-recipes-db-docker